FROM postgres:13.3-alpine
COPY ./sql/*.sql /docker-entrypoint-initdb.d/
# # Habilitar todos los permisos a la carpeta de arranque de la BD
# RUN chmod a+r /docker-entrypoint-initdb.d/*
# RUN chmod a+r /docker-entrypoint-initdb.d/

# ENV PGDATA=/data
ENV LANG es_ES.utf8