swagger: "2.0"
info:
  description: "Swagger document for Survivor battle royale"
  version: "1.0.0"
  title: "BlackMouth Test"

paths:
  /api/players:
    get:
      summary: "Get all players"
      responses:
        200:
          description: "Successful operation"
    post:
      summary: "Create a new player"
      responses:
        201:
          description: "Player created"
    put:
      summary: "Update a player by ID"
      parameters:
        - name: id
          in: path
          description: "ID of the player to update"
          required: true
          type: string
      responses:
        200:
          description: "Player updated"
        404:
          description: "Player not found"
    delete:
      summary: "delete a new player"
      responses:
        201:
          description: "Player Deleted"
  /api/players/{id}:
    get:
      summary: "Get a player by ID"
      parameters:
        - name: id
          in: path
          description: "ID of the player to retrieve"
          required: true
          type: string
      responses:
        200:
          description: "Successful operation"
        204:
          description: "Player not found"

definitions:
  Player:
    type: object
    properties:
      name:
        type: string
